hydra:
  run:
    dir: outputs/la_e_rls/${now:%Y-%m-%d}/${now:%H-%M-%S}

wandb:
  project: "one-pass-distill"
  entity: null
  name: "LA-E-RLS_${now:%Y-%m-%d_%H-%M-%S}"
  mode: "online"

data:
  batch_size: 64
  num_workers: 24
  dataset_name: cifar100

model:
  name: resnet20
  num_classes: 100

train:
  epochs: 240
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0001
  
la_e_rls:
  alpha_min: 0.02
  alpha_max: 0.12
  h_min: 0.5
  h_max: 2.5
  tau_min: 0.5
  tau_max: 5.0
  lambda_val: 0.5
  tau_kd: 4.0
  power_law_exp: 2.0
  distribution_type: "dirichlet" # Options: "power_law", "dirichlet"
  dirichlet_beta: 0.0 # 0.0 or negative -> Auto 1/C (Ideal for sparsity)
  bs_iters: 15
  seed: 42
  sorting_mode: "fully_sorted" # Options: "fully_sorted", "gt_anchored"
  lambda_schedule: "adaptive" # Options: "cosine", "adaptive"
  dry_run: false
